### ISSUE TITLE
Index File on Front

### ISSUE THREAD

**Issue by abhigyan-c** [abhigyan-c/wanderer#1]
Need to put index.html in the front, not the HTML folder. Otherwise I cannot host it on github.io. But the problem is that the CSS and other stuff aren't loading when I do that. Please fix.

**Comment by abhigyan-c** [comment]
So as it turns out we have to name the repo as "username.github.io" and then put the index.html there. Any ideas?

**Comment by Ritavas1** [comment]
Did you issue the Github page?

**Comment by Ritavas1** [comment]
> Need to put index.html in the front, not the HTML folder. Otherwise I cannot host it on github.io. But the problem is that the CSS and other stuff aren't loading when I do that. Please fix.
