### ISSUE TITLE
[Enchanement] Code Documentation

### ISSUE THREAD

**Issue by aviiciii** [abhigyan-c/wanderer#17]
### Describe the bug
No Descriptions on the code blocks or snippets. Only identifier is the class of the html conponents.

### To Reproduce
1.Open the source in an editor

### Expected behavior
Need short description on code blocks to quickly grasp the structure of the code

**Comment by satatya** [comment]
i'll look into it ..

**Comment by aviiciii** [comment]
@satatya I am working to fix this issue. Kindly check for other issues to fix.

**Comment by aviiciii** [comment]
This issue has been completed through pull requests :
- #24 
- #25 
- #26 
- #27 
- #34 
All HTML, JAVASCRIPT, CSS files have been formatted properly and been merged into main.
