### ISSUE TITLE
Homepage section optimisation

### ISSUE THREAD

**Issue by satatya** [abhigyan-c/wanderer#22]
A section of home-page, titled Hotel facilities, needs to be optimized for all devices(pc/android/iOS). Currently, that section is bugged, as we can view the title is also not centred properly. Add media queries to fix the device optimization and also try to fix the bug for the centred title "Hotel facilities".

**Comment by satatya** [comment]
![h_facilities](https://user-images.githubusercontent.com/96868378/217509567-3cdfa720-c3ae-4db0-b8b0-9cef39cbb1fa.png)

**Comment by satatya** [comment]
![image](https://user-images.githubusercontent.com/96868378/217510062-800ab9ac-70b5-4264-9908-aecae460a0fc.png)

**Comment by satatya** [comment]
@aviiciii @Tapo41 @Hitanshi-Singh anyone of you guys interested in resolving this issue?

**Comment by Tapo41** [comment]
@satatya  I'm interested, you cn assign it to me

**Comment by satatya** [comment]
Ok sure then, go ahead @Tapo41 ... Thank u..

**Comment by Tapo41** [comment]
#36  Solved
@satatya

**Comment by satatya** [comment]
Thank You so much!

**Comment by Tapo41** [comment]
@satatya  most welcome
