### ISSUE TITLE
Log size is to big, need to decrease size

### ISSUE THREAD

**Issue by devvsakib** [abhigyan-c/wanderer#43]
PR #42 

![image](https://user-images.githubusercontent.com/88339569/218322227-cf9a99d2-a363-4b37-aa41-2574306304b9.png)

**Comment by satatya** [comment]
Not required, Pls find another issue to contribute, or refer to issues already open,

**Comment by devvsakib** [comment]
It's okay, though it doesn't look nice.

**Comment by satatya** [comment]
don't need to worry about that...
